### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Kup1ng** [mikeesierrah/ez-warp#1]
سلام، خسته نباشید
اول تشکر میکنم از زحماتی که میکشید
دوم هم یک درخواتس داشتم که اگر ممکنه امکان ایپی چنج را به اسکریپت اضافه کنید عالی میشه
ممنون

**Comment by Kup1ng** [comment]
مثلا وقتی دستور wg را زدیم چنتا اپشن بیاد مثل تغییر ایپی - تغییر لایسنس - نصب مجدد - پاک کردن

**Comment by mikeesierrah** [comment]
سلام وقت بخیر ، همچین امکانی وجود نداره چون این دستور بخشی از هسته خود وایرگارده و باید ی سری دستورات دیگه اضافه کنم ولی بهش فکر میکنم چشم
