### ISSUE TITLE
Exclude smtp port

### ISSUE THREAD

**Issue by shiwildy** [mikeesierrah/ez-warp#2]
Hello, is possible to excluding port 25 and other SMTP port from wireguard tunnel in linux ?

**Comment by mikeesierrah** [comment]
Well yes since it just adds an interface - you have to specify in your apps that you want to use warp interface or not

**Comment by shiwildy** [comment]
do you have example?
how to implement it on linux ?

**Comment by mikeesierrah** [comment]
sadly no since i haven't tried - wasn't google any help?

**Comment by shiwildy** [comment]
> sadly no since i havent tried - wasnt google anyhelp?

I have tried various methods on google but none of them working
