### ISSUE TITLE
error while installing 

### ISSUE THREAD

**Issue by jellyenderson** [mikeesierrah/ez-warp#5]
--2024-11-01 23:52:06--  https://github.com/ViRb3/wgcf/releases/download/v2.2.23/wgcf_2.2.19_linux_amd64
Resolving github.com (github.com)... 20.233.83.145
Connecting to github.com (github.com)|20.233.83.145|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-11-01 23:52:11 ERROR 404: Not Found.

**Comment by mikeesierrah** [comment]
Sorry ,there was a problem with installation link and was fixed immediately after 
thanks for feedback tho
